### ISSUE TITLE
No dependency check

### ISSUE THREAD

**Issue by gingerbenw** [mattpocock/boilersuit#1]
After generating a suit of actions/reducers from a clean boilerplate, the selector attempts to use `selectDomain` and `fromJS` without ensuring they are imported first.

**Comment by mattpocock** [comment]
Note to self - change selectDomain to `select${containerName}Domain`

**Comment by mattpocock** [comment]
I have put in a fix for the fromJS error. Version is 0.0.7. Go to your local install, git pull and npm i -g should work.

**Comment by mattpocock** [comment]
Fixed as of 0.1.0
